

/* WARNING - DO NOT EDIT FILE - FILE IS AUTO GENERATED BY FUNCTIONS2CPP.PL*/

/***************************************************************************
 *
 * Project:  OpenCPN
 * Purpose:  ROUTE Plugin
 * Author:   SaltyPaws
 *
 ***************************************************************************
 *   Copyright (C) 2012 by Brazil BrokeTail                                *
 *   $EMAIL$                                                               *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************
 */

#include "functions.h"

 CFormula::CFormula(void)
{
    this->Selected_Formula = 1;

this->m_ShortDesc.Add(_("Hull Speed (imperial)"));
this->m_LongDesc.Add(_("Hull speed, sometimes referred to as displacement speed, can be thought of the speed at which the wavelength of the boats bow wave (in displacement mode) is equal to the boat length. As boat speed increases, the size of the bow wave increases, and therefore so does its wavelength. When hull speed is reached, a boat in pure displacement mode will appear trapped in a trough behind its very large bow wave."));
this->m_Category.Add(_("Design"));
this->m_Source.Add(_("http://www.bootkeyharbor.com/Formulas.htm"));
this->m_Formula.Add(_("vhull=1.34*sqrt(LWL)"));
this->m_Result_Unit.Add(_("feet"));
this->m_Input_parameter.Add(_("LWL"));
this->m_Input_unit.Add(_("feet"));
this->m_Input_parameter1.Add(_(""));
this->m_Input_unit1.Add(_(""));
this->m_Input_parameter2.Add(_(""));
this->m_Input_unit2.Add(_(""));
this->m_Input_parameter3.Add(_(""));
this->m_Input_unit3.Add(_(""));
this->m_Input_parameter4.Add(_(""));
this->m_Input_unit4.Add(_(""));
this->m_Input_parameter5.Add(_(""));
this->m_Input_unit5.Add(_(""));
this->m_Input_parameter6.Add(_(""));
this->m_Input_unit6.Add(_(""));
this->m_Input_parameter7.Add(_(""));
this->m_Input_unit7.Add(_(""));
this->m_Input_parameter8.Add(_(""));
this->m_Input_unit8.Add(_(""));
this->m_Input_parameter9.Add(_(""));
this->m_Input_unit9.Add(_(""));

this->m_ShortDesc.Add(_("Hull Speed (metric)"));
this->m_LongDesc.Add(_("Hull speed, sometimes referred to as displacement speed, can be thought of the speed at which the wavelength of the boats bow wave (in displacement mode) is equal to the boat length. As boat speed increases, the size of the bow wave increases, and therefore so does its wavelength. When hull speed is reached, a boat in pure displacement mode will appear trapped in a trough behind its very large bow wave."));
this->m_Category.Add(_("Design"));
this->m_Source.Add(_("http://www.bootkeyharbor.com/Formulas.htm"));
this->m_Formula.Add(_("vhull=1.34*sqrt(LWL/0.3048)"));
this->m_Result_Unit.Add(_("meter"));
this->m_Input_parameter.Add(_("LWL"));
this->m_Input_unit.Add(_("meter"));
this->m_Input_parameter1.Add(_(""));
this->m_Input_unit1.Add(_(""));
this->m_Input_parameter2.Add(_(""));
this->m_Input_unit2.Add(_(""));
this->m_Input_parameter3.Add(_(""));
this->m_Input_unit3.Add(_(""));
this->m_Input_parameter4.Add(_(""));
this->m_Input_unit4.Add(_(""));
this->m_Input_parameter5.Add(_(""));
this->m_Input_unit5.Add(_(""));
this->m_Input_parameter6.Add(_(""));
this->m_Input_unit6.Add(_(""));
this->m_Input_parameter7.Add(_(""));
this->m_Input_unit7.Add(_(""));
this->m_Input_parameter8.Add(_(""));
this->m_Input_unit8.Add(_(""));
this->m_Input_parameter9.Add(_(""));
this->m_Input_unit9.Add(_(""));

this->m_ShortDesc.Add(_("Draft of vessel when heeled"));
this->m_LongDesc.Add(_("Draft of vessel when heeled"));
this->m_Category.Add(_("Navigation"));
this->m_Source.Add(_("http://www.bootkeyharbor.com/Formulas.htm"));
this->m_Formula.Add(_("draft_heeled=draft*cos(dtr*angle)"));
this->m_Result_Unit.Add(_("As Input units draft"));
this->m_Input_parameter.Add(_("angle"));
this->m_Input_unit.Add(_("Degree (\u00b0)"));
this->m_Input_parameter1.Add(_("draft"));
this->m_Input_unit1.Add(_("As output units"));
this->m_Input_parameter2.Add(_(""));
this->m_Input_unit2.Add(_(""));
this->m_Input_parameter3.Add(_(""));
this->m_Input_unit3.Add(_(""));
this->m_Input_parameter4.Add(_(""));
this->m_Input_unit4.Add(_(""));
this->m_Input_parameter5.Add(_(""));
this->m_Input_unit5.Add(_(""));
this->m_Input_parameter6.Add(_(""));
this->m_Input_unit6.Add(_(""));
this->m_Input_parameter7.Add(_(""));
this->m_Input_unit7.Add(_(""));
this->m_Input_parameter8.Add(_(""));
this->m_Input_unit8.Add(_(""));
this->m_Input_parameter9.Add(_(""));
this->m_Input_unit9.Add(_(""));

this->m_ShortDesc.Add(_("Speed of wind-driven current"));
this->m_LongDesc.Add(_("Speed of wind-driven current"));
this->m_Category.Add(_("Navigation"));
this->m_Source.Add(_("http://www.bootkeyharbor.com/Formulas.htm"));
this->m_Formula.Add(_("Speed_Current = 0.03 * (Speed_Wind)"));
this->m_Result_Unit.Add(_("knots"));
this->m_Input_parameter.Add(_("Speed_Wind"));
this->m_Input_unit.Add(_("knots"));
this->m_Input_parameter1.Add(_(""));
this->m_Input_unit1.Add(_(""));
this->m_Input_parameter2.Add(_(""));
this->m_Input_unit2.Add(_(""));
this->m_Input_parameter3.Add(_(""));
this->m_Input_unit3.Add(_(""));
this->m_Input_parameter4.Add(_(""));
this->m_Input_unit4.Add(_(""));
this->m_Input_parameter5.Add(_(""));
this->m_Input_unit5.Add(_(""));
this->m_Input_parameter6.Add(_(""));
this->m_Input_unit6.Add(_(""));
this->m_Input_parameter7.Add(_(""));
this->m_Input_unit7.Add(_(""));
this->m_Input_parameter8.Add(_(""));
this->m_Input_unit8.Add(_(""));
this->m_Input_parameter9.Add(_(""));
this->m_Input_unit9.Add(_(""));

this->m_ShortDesc.Add(_("Maximum Wavelength"));
this->m_LongDesc.Add(_("Maximum Wavelength = 1.5 x square root of fetch in nm"));
this->m_Category.Add(_("Navigation"));
this->m_Source.Add(_("http://www.bootkeyharbor.com/Formulas.htm"));
this->m_Formula.Add(_("Maximum_Wavelength = 1.5 * sqrt(fetch)"));
this->m_Result_Unit.Add(_(""));
this->m_Input_parameter.Add(_("fetch"));
this->m_Input_unit.Add(_("NM"));
this->m_Input_parameter1.Add(_(""));
this->m_Input_unit1.Add(_(""));
this->m_Input_parameter2.Add(_(""));
this->m_Input_unit2.Add(_(""));
this->m_Input_parameter3.Add(_(""));
this->m_Input_unit3.Add(_(""));
this->m_Input_parameter4.Add(_(""));
this->m_Input_unit4.Add(_(""));
this->m_Input_parameter5.Add(_(""));
this->m_Input_unit5.Add(_(""));
this->m_Input_parameter6.Add(_(""));
this->m_Input_unit6.Add(_(""));
this->m_Input_parameter7.Add(_(""));
this->m_Input_unit7.Add(_(""));
this->m_Input_parameter8.Add(_(""));
this->m_Input_unit8.Add(_(""));
this->m_Input_parameter9.Add(_(""));
this->m_Input_unit9.Add(_(""));

this->m_ShortDesc.Add(_("Wave speed =f(period)"));
this->m_LongDesc.Add(_("Wave speed = 3.03 x (wave period in seconds)"));
this->m_Category.Add(_("Navigation"));
this->m_Source.Add(_("http://www.bootkeyharbor.com/Formulas.htm"));
this->m_Formula.Add(_("Wave_speed = 3.03 * (wave_period)"));
this->m_Result_Unit.Add(_("knots"));
this->m_Input_parameter.Add(_("wave_period"));
this->m_Input_unit.Add(_("seconds"));
this->m_Input_parameter1.Add(_(""));
this->m_Input_unit1.Add(_(""));
this->m_Input_parameter2.Add(_(""));
this->m_Input_unit2.Add(_(""));
this->m_Input_parameter3.Add(_(""));
this->m_Input_unit3.Add(_(""));
this->m_Input_parameter4.Add(_(""));
this->m_Input_unit4.Add(_(""));
this->m_Input_parameter5.Add(_(""));
this->m_Input_unit5.Add(_(""));
this->m_Input_parameter6.Add(_(""));
this->m_Input_unit6.Add(_(""));
this->m_Input_parameter7.Add(_(""));
this->m_Input_unit7.Add(_(""));
this->m_Input_parameter8.Add(_(""));
this->m_Input_unit8.Add(_(""));
this->m_Input_parameter9.Add(_(""));
this->m_Input_unit9.Add(_(""));

this->m_ShortDesc.Add(_("Change in height of Tide"));
this->m_LongDesc.Add(_("Height is total change in tide heigt between high and low. The time ratio is time elapsed from the previous tide divided by the time difference between the two tides. (Similar to rule of 12)"));
this->m_Category.Add(_("Navigation"));
this->m_Source.Add(_("http://www.bootkeyharbor.com/Formulas.htm"));
this->m_Formula.Add(_("Change_in_height_of_Tide = height/2 * (1-cos(dtr(180) * time_ratio))"));
this->m_Result_Unit.Add(_("As Input units height"));
this->m_Input_parameter.Add(_("height"));
this->m_Input_unit.Add(_("As Output units"));
this->m_Input_parameter1.Add(_("time_ratio"));
this->m_Input_unit1.Add(_("-"));
this->m_Input_parameter2.Add(_(""));
this->m_Input_unit2.Add(_(""));
this->m_Input_parameter3.Add(_(""));
this->m_Input_unit3.Add(_(""));
this->m_Input_parameter4.Add(_(""));
this->m_Input_unit4.Add(_(""));
this->m_Input_parameter5.Add(_(""));
this->m_Input_unit5.Add(_(""));
this->m_Input_parameter6.Add(_(""));
this->m_Input_unit6.Add(_(""));
this->m_Input_parameter7.Add(_(""));
this->m_Input_unit7.Add(_(""));
this->m_Input_parameter8.Add(_(""));
this->m_Input_unit8.Add(_(""));
this->m_Input_parameter9.Add(_(""));
this->m_Input_unit9.Add(_(""));

this->m_ShortDesc.Add(_("Flow rate of leak in boat"));
this->m_LongDesc.Add(_("Flow rate of leak in boat:\tQ = 3,600 (A) (H)\n\tQ = gallons per minute of water coming in\n\tA = area of hole in square feet\n\tH = height of water over hole in feet, to bottom of the opening"));
this->m_Category.Add(_("Safety"));
this->m_Source.Add(_("http://www.bootkeyharbor.com/Formulas.htm"));
this->m_Formula.Add(_("Q = 3600 *(A)* (H)"));
this->m_Result_Unit.Add(_("gallons per minute"));
this->m_Input_parameter.Add(_("A"));
this->m_Input_unit.Add(_("square feet"));
this->m_Input_parameter1.Add(_("H"));
this->m_Input_unit1.Add(_("feet"));
this->m_Input_parameter2.Add(_(""));
this->m_Input_unit2.Add(_(""));
this->m_Input_parameter3.Add(_(""));
this->m_Input_unit3.Add(_(""));
this->m_Input_parameter4.Add(_(""));
this->m_Input_unit4.Add(_(""));
this->m_Input_parameter5.Add(_(""));
this->m_Input_unit5.Add(_(""));
this->m_Input_parameter6.Add(_(""));
this->m_Input_unit6.Add(_(""));
this->m_Input_parameter7.Add(_(""));
this->m_Input_unit7.Add(_(""));
this->m_Input_parameter8.Add(_(""));
this->m_Input_unit8.Add(_(""));
this->m_Input_parameter9.Add(_(""));
this->m_Input_unit9.Add(_(""));

this->m_ShortDesc.Add(_("Patch over hole"));
this->m_LongDesc.Add(_("Patch or cover thickness to withstand water pressure (patch over hole):\n\n\tT = square root of:\t(48x (H) (L2))/ 1000)\n\tT = thickness of wood or plywood patch in inches\n\tH = height of water above bottom of hole, in feet\n\tL = length of patch, longest distance between supports, in feet"));
this->m_Category.Add(_("Safety"));
this->m_Source.Add(_("http://www.bootkeyharbor.com/Formulas.htm"));
this->m_Formula.Add(_("T = sqrt( (48* H* (L^2))/1000)"));
this->m_Result_Unit.Add(_("inch"));
this->m_Input_parameter.Add(_("H"));
this->m_Input_unit.Add(_("feet"));
this->m_Input_parameter1.Add(_("L"));
this->m_Input_unit1.Add(_("feet"));
this->m_Input_parameter2.Add(_(""));
this->m_Input_unit2.Add(_(""));
this->m_Input_parameter3.Add(_(""));
this->m_Input_unit3.Add(_(""));
this->m_Input_parameter4.Add(_(""));
this->m_Input_unit4.Add(_(""));
this->m_Input_parameter5.Add(_(""));
this->m_Input_unit5.Add(_(""));
this->m_Input_parameter6.Add(_(""));
this->m_Input_unit6.Add(_(""));
this->m_Input_parameter7.Add(_(""));
this->m_Input_unit7.Add(_(""));
this->m_Input_parameter8.Add(_(""));
this->m_Input_unit8.Add(_(""));
this->m_Input_parameter9.Add(_(""));
this->m_Input_unit9.Add(_(""));

this->m_ShortDesc.Add(_("Line Break strength (diameter)"));
this->m_LongDesc.Add(_("Each type of line, natural fiber, synthetic and wire rope, have different breaking strengths and safe working loads. Natural breaking strength of manila line is the standard against which other lines are compared. Synthetic lines have been assigned comparison factors against which they are compared to manila line. The basic breaking strength factor for manila line is found by multiplying the square of the circumference of the line by 900 lbs. Knots and splices only have 50-60 of line strenght.\n\tLine Material\tComparison Factor \n\tNylon\t\t\t\t\t2.5\n\tDacron\t\t\t\t2.0\n\tPolypropylene\t\t1.4\n\tManilla \t\t\t\t1.0"));
this->m_Category.Add(_("Safety"));
this->m_Source.Add(_("http://www.boatsafe.com/marlinespike/breaking.htm"));
this->m_Formula.Add(_("breaking_strength= 900 * comparison_factor * circumference^2 "));
this->m_Result_Unit.Add(_("lbs"));
this->m_Input_parameter.Add(_("comparison_factor"));
this->m_Input_unit.Add(_("See table"));
this->m_Input_parameter1.Add(_("circumference"));
this->m_Input_unit1.Add(_("inch"));
this->m_Input_parameter2.Add(_(""));
this->m_Input_unit2.Add(_(""));
this->m_Input_parameter3.Add(_(""));
this->m_Input_unit3.Add(_(""));
this->m_Input_parameter4.Add(_(""));
this->m_Input_unit4.Add(_(""));
this->m_Input_parameter5.Add(_(""));
this->m_Input_unit5.Add(_(""));
this->m_Input_parameter6.Add(_(""));
this->m_Input_unit6.Add(_(""));
this->m_Input_parameter7.Add(_(""));
this->m_Input_unit7.Add(_(""));
this->m_Input_parameter8.Add(_(""));
this->m_Input_unit8.Add(_(""));
this->m_Input_parameter9.Add(_(""));
this->m_Input_unit9.Add(_(""));

this->m_ShortDesc.Add(_("Line Break strength (circumference)"));
this->m_LongDesc.Add(_("Each type of line, natural fiber, synthetic and wire rope, have different breaking strengths and safe working loads. Natural breaking strength of manila line is the standard against which other lines are compared. Synthetic lines have been assigned comparison factors against which they are compared to manila line. The basic breaking strength factor for manila line is found by multiplying the square of the circumference of the line by 900 lbs. Knots and splices only have 50-60 of line strenght.\n\tLine Material\tComparison Factor \n\tNylon\t\t\t\t\t2.5\n\tDacron\t\t\t\t2.0\n\tPolypropylene\t\t1.4\n\tManilla \t\t\t\t1.0"));
this->m_Category.Add(_("Safety"));
this->m_Source.Add(_("http://www.boatsafe.com/marlinespike/breaking.htm"));
this->m_Formula.Add(_("breaking_strength= 900 * comparison_factor * (pi*diameter)^2 "));
this->m_Result_Unit.Add(_("lbs"));
this->m_Input_parameter.Add(_("comparison_factor"));
this->m_Input_unit.Add(_("See table"));
this->m_Input_parameter1.Add(_("diameter"));
this->m_Input_unit1.Add(_("inch"));
this->m_Input_parameter2.Add(_(""));
this->m_Input_unit2.Add(_(""));
this->m_Input_parameter3.Add(_(""));
this->m_Input_unit3.Add(_(""));
this->m_Input_parameter4.Add(_(""));
this->m_Input_unit4.Add(_(""));
this->m_Input_parameter5.Add(_(""));
this->m_Input_unit5.Add(_(""));
this->m_Input_parameter6.Add(_(""));
this->m_Input_unit6.Add(_(""));
this->m_Input_parameter7.Add(_(""));
this->m_Input_unit7.Add(_(""));
this->m_Input_parameter8.Add(_(""));
this->m_Input_unit8.Add(_(""));
this->m_Input_parameter9.Add(_(""));
this->m_Input_unit9.Add(_(""));

this->m_ShortDesc.Add(_("Velocity Made Good (angle)"));
this->m_LongDesc.Add(_("Velocity made good, or vmg, is a term in sailing, and specifically yacht racing, that refers to the component of a sailboats velocity that is in the direction of the true wind. The concept is useful in sailing, because a sailboat often cannot, or should not, sail directly to a mark to reach the mark as quickly as possible. Sailboats cannot sail directly upwind, and it is usually less than optimal, and sometimes dangerous, to sail directly downwind. Instead of sailing toward the mark, the helmsman chooses a point of sail that optimizes velocity made good."));
this->m_Category.Add(_("Navigation"));
this->m_Source.Add(_("http://lagoon-inside.com/2012/01/faster-thanks-to-the-vmg-concept/"));
this->m_Formula.Add(_("VMG=V*cos(alpha*dtr)"));
this->m_Result_Unit.Add(_("Knots"));
this->m_Input_parameter.Add(_("V"));
this->m_Input_unit.Add(_("Knots"));
this->m_Input_parameter1.Add(_("alpha"));
this->m_Input_unit1.Add(_("Degree (\u00b0)"));
this->m_Input_parameter2.Add(_(""));
this->m_Input_unit2.Add(_(""));
this->m_Input_parameter3.Add(_(""));
this->m_Input_unit3.Add(_(""));
this->m_Input_parameter4.Add(_(""));
this->m_Input_unit4.Add(_(""));
this->m_Input_parameter5.Add(_(""));
this->m_Input_unit5.Add(_(""));
this->m_Input_parameter6.Add(_(""));
this->m_Input_unit6.Add(_(""));
this->m_Input_parameter7.Add(_(""));
this->m_Input_unit7.Add(_(""));
this->m_Input_parameter8.Add(_(""));
this->m_Input_unit8.Add(_(""));
this->m_Input_parameter9.Add(_(""));
this->m_Input_unit9.Add(_(""));

this->m_ShortDesc.Add(_("Velocity Made Good (delta)"));
this->m_LongDesc.Add(_("Velocity made good, or vmg, is a term in sailing, and specifically yacht racing, that refers to the component of a sailboats velocity that is in the direction of the true wind. The concept is useful in sailing, because a sailboat often cannot, or should not, sail directly to a mark to reach the mark as quickly as possible. Sailboats cannot sail directly upwind, and it is usually less than optimal, and sometimes dangerous, to sail directly downwind. Instead of sailing toward the mark, the helmsman chooses a point of sail that optimizes velocity made good."));
this->m_Category.Add(_("Navigation"));
this->m_Source.Add(_("http://lagoon-inside.com/2012/01/faster-thanks-to-the-vmg-concept/"));
this->m_Formula.Add(_("VMG=V*cos((alpha1-alpha2)*dtr)"));
this->m_Result_Unit.Add(_("Knots"));
this->m_Input_parameter.Add(_("V"));
this->m_Input_unit.Add(_("Knots"));
this->m_Input_parameter1.Add(_("alpha1"));
this->m_Input_unit1.Add(_("Degree (\u00b0)"));
this->m_Input_parameter2.Add(_("alpha2"));
this->m_Input_unit2.Add(_("Degree (\u00b0)"));
this->m_Input_parameter3.Add(_(""));
this->m_Input_unit3.Add(_(""));
this->m_Input_parameter4.Add(_(""));
this->m_Input_unit4.Add(_(""));
this->m_Input_parameter5.Add(_(""));
this->m_Input_unit5.Add(_(""));
this->m_Input_parameter6.Add(_(""));
this->m_Input_unit6.Add(_(""));
this->m_Input_parameter7.Add(_(""));
this->m_Input_unit7.Add(_(""));
this->m_Input_parameter8.Add(_(""));
this->m_Input_unit8.Add(_(""));
this->m_Input_parameter9.Add(_(""));
this->m_Input_unit9.Add(_(""));

this->m_ShortDesc.Add(_("test"));
this->m_LongDesc.Add(_("test"));
this->m_Category.Add(_("test"));
this->m_Source.Add(_("test"));
this->m_Formula.Add(_("a=b+c+d+e+f+g+h+I+j+k+l+m+n+o+p+r+s"));
this->m_Result_Unit.Add(_("aa"));
this->m_Input_parameter.Add(_("b"));
this->m_Input_unit.Add(_("bb"));
this->m_Input_parameter1.Add(_("c"));
this->m_Input_unit1.Add(_("cc"));
this->m_Input_parameter2.Add(_("d"));
this->m_Input_unit2.Add(_("dd"));
this->m_Input_parameter3.Add(_("e"));
this->m_Input_unit3.Add(_("ee"));
this->m_Input_parameter4.Add(_("f"));
this->m_Input_unit4.Add(_("ff"));
this->m_Input_parameter5.Add(_("g"));
this->m_Input_unit5.Add(_("gg"));
this->m_Input_parameter6.Add(_("h"));
this->m_Input_unit6.Add(_("hh"));
this->m_Input_parameter7.Add(_("I"));
this->m_Input_unit7.Add(_("ii"));
this->m_Input_parameter8.Add(_("j"));
this->m_Input_unit8.Add(_("jj"));
this->m_Input_parameter9.Add(_("k"));
this->m_Input_unit9.Add(_("kk"));





































}

