/* Autogenerated by png2wx.pl on Tue Jul 24 22:03:56 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_calc;
extern wxBitmap *_img_psd_calculator_web_icon_blue2;

#endif /* ICONS_H */
