 /* WARNING - DO NOT EDIT FILE - FILE IS AUTO GENERATED BY FUNCTIONS2CPP.PL*/
  /***************************************************************************
  *
  * Project:  OpenCPN
  * Purpose:  ROUTE Plugin
  * Author:   SaltyPaws
  *
  ***************************************************************************
  *   Copyright (C) 2012 by Brazil BrokeTail                                *
  *   $EMAIL$                                                               *
  *                                                                         *
  *   This program is free software; you can redistribute it and/or modify  *
  *   it under the terms of the GNU General Public License as published by  *
  *   the Free Software Foundation; either version 2 of the License, or     *
  *   (at your option) any later version.                                   *
  *                                                                         *
  *   This program is distributed in the hope that it will be useful,       *
  *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
  *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
  *   GNU General Public License for more details.                          *
  *                                                                         *
  *   You should have received a copy of the GNU General Public License     *
  *   along with this program; if not, write to the                         *
  *   Free Software Foundation, Inc.,                                       *
  *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
  ***************************************************************************
  */

#include "units_conversion.h"
Units_Conversion::Units_Conversion(void)
{

this->m_Unit.Add(_("Degree (\u00b0)"));
this->m_Unit_category.Add(_("Angle"));
this->m_Conversion.Add(_("1"));
this->m_Display.Add(_("TRUE"));

this->m_Unit.Add(_("Radians"));
this->m_Unit_category.Add(_("Angle"));
this->m_Conversion.Add(_("VAR/dtr=VAR*dtr"));
this->m_Display.Add(_("TRUE"));

this->m_Unit.Add(_("Degree"));
this->m_Unit_category.Add(_("Angle"));
this->m_Conversion.Add(_("1"));
this->m_Display.Add(_("FALSE"));

this->m_Unit.Add(_("Meter"));
this->m_Unit_category.Add(_("Distance"));
this->m_Conversion.Add(_("1"));
this->m_Display.Add(_("TRUE"));

this->m_Unit.Add(_("Nautical Miles"));
this->m_Unit_category.Add(_("Distance"));
this->m_Conversion.Add(_("1852"));
this->m_Display.Add(_("TRUE"));

this->m_Unit.Add(_("inch"));
this->m_Unit_category.Add(_("Distance"));
this->m_Conversion.Add(_("0.0254"));
this->m_Display.Add(_("TRUE"));

this->m_Unit.Add(_("feet"));
this->m_Unit_category.Add(_("Distance"));
this->m_Conversion.Add(_("0.3048"));
this->m_Display.Add(_("TRUE"));

this->m_Unit.Add(_("kilometer"));
this->m_Unit_category.Add(_("Distance"));
this->m_Conversion.Add(_("1000"));
this->m_Display.Add(_("TRUE"));

this->m_Unit.Add(_("Metre"));
this->m_Unit_category.Add(_("Distance"));
this->m_Conversion.Add(_("1"));
this->m_Display.Add(_("FALSE"));

this->m_Unit.Add(_("foot"));
this->m_Unit_category.Add(_("Distance"));
this->m_Conversion.Add(_("0.3048"));
this->m_Display.Add(_("FALSE"));

this->m_Unit.Add(_("Fathom"));
this->m_Unit_category.Add(_("Distance"));
this->m_Conversion.Add(_("1.8288"));
this->m_Display.Add(_("FALSE"));

this->m_Unit.Add(_("m/s"));
this->m_Unit_category.Add(_("Speed"));
this->m_Conversion.Add(_("1"));
this->m_Display.Add(_("TRUE"));

this->m_Unit.Add(_("Knots"));
this->m_Unit_category.Add(_("Speed"));
this->m_Conversion.Add(_("0.514444"));
this->m_Display.Add(_("TRUE"));

this->m_Unit.Add(_("km/h"));
this->m_Unit_category.Add(_("Speed"));
this->m_Conversion.Add(_("0.277778"));
this->m_Display.Add(_("TRUE"));

this->m_Unit.Add(_("Celsius"));
this->m_Unit_category.Add(_("Temperature"));
this->m_Conversion.Add(_("1"));
this->m_Display.Add(_("TRUE"));

this->m_Unit.Add(_("Kelvin"));
this->m_Unit_category.Add(_("Temperature"));
this->m_Conversion.Add(_("VAR - 273.15 = VAR + 273.15 "));
this->m_Display.Add(_("TRUE"));

this->m_Unit.Add(_("Fahrenheit"));
this->m_Unit_category.Add(_("Temperature"));
this->m_Conversion.Add(_("(5/9) * (VAR\t32)=(9/5)* (VAR+32)"));
this->m_Display.Add(_("TRUE"));

this->m_Unit.Add(_("Rankine"));
this->m_Unit_category.Add(_("Temperature"));
this->m_Conversion.Add(_("(VAR491.67)*5 D9=(VAR + 273.15) * (9 D5)"));
this->m_Display.Add(_("TRUE"));

 //End Class

}